version: '3.7'
services:
  server:
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - grpc

  grpc:
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - '8081:8081'